import { NextRequest, NextResponse } from 'next/server';
import { getServerSupabase } from '@/lib/supabase';
import puppeteer from 'puppeteer-core';
import chromium from '@sparticuz/chromium';

export const runtime = 'nodejs';
export const maxDuration = 60;

function esc(v: any): string {
  if (v == null) return '';
  return String(v).replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
}

function row(label: string, value: any): string {
  return `<tr><th>${esc(label)}</th><td>${esc(value || 'not documented')}</td></tr>`;
}

function buildHtml(p: any): string {
  // PINNED layout. Do NOT regenerate HTML structure per export.
  return `<!doctype html><html><head><meta charset="utf-8" />
<title>PCR Pilot — Demo Report</title>
<style>
  * { box-sizing: border-box; }
  body { font: 12px/1.4 -apple-system, system-ui, "Segoe UI", Arial, sans-serif; color:#0f172a; padding: 24px; margin:0; }
  h1 { font-size: 18px; margin: 0 0 4px; color: #0B5FFF; }
  .sub { color:#64748b; font-size: 11px; margin-bottom: 12px; }
  .demo { background:#fff7ed; color:#9a3412; border:1px solid #fed7aa; padding: 6px 10px;
          font-weight: 600; font-size: 11px; border-radius: 6px; margin-bottom: 12px; }
  table { width:100%; border-collapse: collapse; margin: 6px 0 10px; }
  th, td { text-align: left; vertical-align: top; padding: 6px 8px; border:1px solid #e5e7eb; font-size: 12px; }
  th { background:#f1f5f9; width: 30%; font-weight: 600; }
  .section { margin-top: 14px; }
  .section h2 { font-size: 13px; margin: 0 0 6px; color:#0B5FFF; border-bottom:1px solid #e5e7eb; padding-bottom: 4px; }
  .narrative { white-space: pre-wrap; padding: 8px; border:1px solid #e5e7eb; border-radius: 6px; background:#fff; }
  .footer { margin-top: 24px; padding-top: 8px; border-top:1px solid #e5e7eb; color:#94a3b8; font-size: 10px; text-align:center; }
  .grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 8px; }
  .sig { padding: 12px; border:1px dashed #cbd5e1; border-radius: 6px; min-height: 56px; }
  .sig-label { font-size: 10px; color:#64748b; margin-bottom: 6px; }
</style></head><body>

<div class="demo">DEMO — Sample data only. Not for real patient information.</div>
<h1>PCR Pilot — DEMO Report</h1>
<div class="sub">Trip Type: <b>${esc(p.trip_type || 'n/a')}</b> · Generated: ${new Date().toLocaleString()}</div>

<div class="section">
  <h2>Patient Information</h2>
  <table>
    ${row('Patient name', p.patient_name)}
    ${row('Date of birth', p.dob)}
    ${row('Age', p.age)}
    ${row('MRN', p.mrn)}
    ${row('Insurance', p.insurance)}
  </table>
</div>

<div class="section">
  <h2>Pickup &amp; Destination</h2>
  <table>
    ${row('Pickup facility', p.pickup_facility)}
    ${row('Pickup address', p.pickup_address)}
    ${row('Pickup time', p.pickup_time)}
    ${row('Destination facility', p.destination_facility)}
    ${row('Destination address', p.destination_address)}
    ${row('Dropoff time', p.dropoff_time)}
  </table>
</div>

<div class="section">
  <h2>Trip Details</h2>
  <table>
    ${row('Mileage', p.mileage)}
    ${row('Reason for transport', p.reason_for_transport)}
    ${row('Diagnosis', p.diagnosis)}
  </table>
</div>

<div class="section">
  <h2>Clinical Narrative</h2>
  <table>
    ${row('Patient condition', p.patient_condition)}
    ${row('Chief complaint', p.chief_complaint)}
    ${row('Assessment', p.assessment)}
    ${row('Mental status', p.mental_status)}
    ${row('Mobility status', p.mobility_status)}
  </table>
</div>

<div class="section">
  <h2>Vitals</h2>
  <div class="narrative">${esc(p.vitals || 'Vitals not provided')}</div>
</div>

<div class="section">
  <h2>Interventions</h2>
  <div class="narrative">${esc(p.interventions || 'No interventions documented')}</div>
</div>

<div class="section">
  <h2>Transfer of Care</h2>
  <div class="narrative">${esc(p.transfer_of_care || 'Transfer of care not documented')}</div>
</div>

<div class="section">
  <h2>Generated Narrative</h2>
  <div class="narrative">${esc(p.generated_narrative || 'Narrative not generated.')}</div>
</div>

<div class="section">
  <h2>Crew Notes</h2>
  <div class="narrative">${esc(p.crew_notes || '—')}</div>
</div>

<div class="section">
  <h2>Signatures</h2>
  <div class="grid2">
    <div class="sig">
      <div class="sig-label">Patient signature ${p.patient_signature_done ? '(✓ on file — DEMO)' : '(missing)'}</div>
    </div>
    <div class="sig">
      <div class="sig-label">Crew signature ${p.crew_signature_done ? '(✓ on file — DEMO)' : '(missing)'}</div>
    </div>
  </div>
</div>

<div class="footer">Demo report — sample data only. Generated by PCR Pilot. Not HIPAA-compliant.</div>
</body></html>`;
}

/**
 * Launch a Chromium instance suitable for the deployment target.
 * - On Vercel/AWS Lambda: uses @sparticuz/chromium (small layered binary).
 * - Locally: respects PUPPETEER_EXECUTABLE_PATH or falls back to default.
 */
async function launchBrowser() {
  const executablePath =
    process.env.PUPPETEER_EXECUTABLE_PATH || (await chromium.executablePath());
  return puppeteer.launch({
    args: chromium.args,
    executablePath,
    headless: true,
    defaultViewport: chromium.defaultViewport,
  });
}

export async function GET(_req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const sb = getServerSupabase();
    const { data: p, error } = await sb.from('pcrs').select('*').eq('id', params.id).maybeSingle();
    if (error) return NextResponse.json({ error: error.message }, { status: 500 });
    if (!p) return NextResponse.json({ error: 'Not found' }, { status: 404 });

    const html = buildHtml(p);
    const browser = await launchBrowser();
    try {
      const page = await browser.newPage();
      await page.setContent(html, { waitUntil: 'networkidle0' });
      const pdf = await page.pdf({ format: 'Letter', printBackground: true,
        margin: { top: '14mm', right: '12mm', bottom: '14mm', left: '12mm' } });
      return new NextResponse(pdf, {
        status: 200,
        headers: {
          'Content-Type': 'application/pdf',
          'Content-Disposition': `attachment; filename="pcr-${params.id}.pdf"`,
          'Cache-Control': 'no-store',
        },
      });
    } finally {
      await browser.close();
    }
  } catch (e: any) {
    return NextResponse.json({ error: e?.message || 'PDF generation failed' }, { status: 500 });
  }
}
